/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.project.drinkingmachine;

import fr.univcotedazur.polytech.si4.fsm.project.ITimer;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public class DrinkingMachineStatemachine implements IDrinkingMachineStatemachine {
	protected class SCInterfaceImpl implements SCInterface {
	
		private List<SCInterfaceListener> listeners = new LinkedList<SCInterfaceListener>();
		
		public List<SCInterfaceListener> getListeners() {
			return listeners;
		}
		private boolean cancelButton;
		
		
		public void raiseCancelButton() {
			synchronized(DrinkingMachineStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							cancelButton = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean boissonButton;
		
		
		public void raiseBoissonButton() {
			synchronized(DrinkingMachineStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							boissonButton = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean slider;
		
		
		public void raiseSlider() {
			synchronized(DrinkingMachineStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							slider = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean nFCButton;
		
		
		public void raiseNFCButton() {
			synchronized(DrinkingMachineStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							nFCButton = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean boissonPrete;
		
		
		public void raiseBoissonPrete() {
			synchronized(DrinkingMachineStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							boissonPrete = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean coinButton;
		
		
		public void raiseCoinButton() {
			synchronized(DrinkingMachineStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							coinButton = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean confirmationLiquide;
		
		
		public void raiseConfirmationLiquide() {
			synchronized(DrinkingMachineStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							confirmationLiquide = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean nettoyageText;
		
		
		public boolean isRaisedNettoyageText() {
			synchronized(DrinkingMachineStatemachine.this) {
				return nettoyageText;
			}
		}
		
		protected void raiseNettoyageText() {
			synchronized(DrinkingMachineStatemachine.this) {
				nettoyageText = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onNettoyageTextRaised();
				}
			}
		}
		
		private boolean doReset;
		
		
		public boolean isRaisedDoReset() {
			synchronized(DrinkingMachineStatemachine.this) {
				return doReset;
			}
		}
		
		protected void raiseDoReset() {
			synchronized(DrinkingMachineStatemachine.this) {
				doReset = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onDoResetRaised();
				}
			}
		}
		
		private boolean prepareBoisson;
		
		
		public boolean isRaisedPrepareBoisson() {
			synchronized(DrinkingMachineStatemachine.this) {
				return prepareBoisson;
			}
		}
		
		protected void raisePrepareBoisson() {
			synchronized(DrinkingMachineStatemachine.this) {
				prepareBoisson = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPrepareBoissonRaised();
				}
			}
		}
		
		private boolean enAttente;
		
		
		public boolean isRaisedEnAttente() {
			synchronized(DrinkingMachineStatemachine.this) {
				return enAttente;
			}
		}
		
		protected void raiseEnAttente() {
			synchronized(DrinkingMachineStatemachine.this) {
				enAttente = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onEnAttenteRaised();
				}
			}
		}
		
		private boolean updateSlider;
		
		
		public boolean isRaisedUpdateSlider() {
			synchronized(DrinkingMachineStatemachine.this) {
				return updateSlider;
			}
		}
		
		protected void raiseUpdateSlider() {
			synchronized(DrinkingMachineStatemachine.this) {
				updateSlider = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onUpdateSliderRaised();
				}
			}
		}
		
		private boolean updateBoisson;
		
		
		public boolean isRaisedUpdateBoisson() {
			synchronized(DrinkingMachineStatemachine.this) {
				return updateBoisson;
			}
		}
		
		protected void raiseUpdateBoisson() {
			synchronized(DrinkingMachineStatemachine.this) {
				updateBoisson = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onUpdateBoissonRaised();
				}
			}
		}
		
		private boolean finishText;
		
		
		public boolean isRaisedFinishText() {
			synchronized(DrinkingMachineStatemachine.this) {
				return finishText;
			}
		}
		
		protected void raiseFinishText() {
			synchronized(DrinkingMachineStatemachine.this) {
				finishText = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onFinishTextRaised();
				}
			}
		}
		
		private boolean lectureCarte;
		
		
		public boolean isRaisedLectureCarte() {
			synchronized(DrinkingMachineStatemachine.this) {
				return lectureCarte;
			}
		}
		
		protected void raiseLectureCarte() {
			synchronized(DrinkingMachineStatemachine.this) {
				lectureCarte = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onLectureCarteRaised();
				}
			}
		}
		
		private boolean increaseCoin;
		
		
		public boolean isRaisedIncreaseCoin() {
			synchronized(DrinkingMachineStatemachine.this) {
				return increaseCoin;
			}
		}
		
		protected void raiseIncreaseCoin() {
			synchronized(DrinkingMachineStatemachine.this) {
				increaseCoin = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onIncreaseCoinRaised();
				}
			}
		}
		
		private boolean renduMonnaie;
		
		
		public boolean isRaisedRenduMonnaie() {
			synchronized(DrinkingMachineStatemachine.this) {
				return renduMonnaie;
			}
		}
		
		protected void raiseRenduMonnaie() {
			synchronized(DrinkingMachineStatemachine.this) {
				renduMonnaie = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onRenduMonnaieRaised();
				}
			}
		}
		
		private boolean paiementNFC;
		
		
		public boolean isRaisedPaiementNFC() {
			synchronized(DrinkingMachineStatemachine.this) {
				return paiementNFC;
			}
		}
		
		protected void raisePaiementNFC() {
			synchronized(DrinkingMachineStatemachine.this) {
				paiementNFC = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPaiementNFCRaised();
				}
			}
		}
		
		private boolean attentePaiement;
		
		
		public boolean isRaisedAttentePaiement() {
			synchronized(DrinkingMachineStatemachine.this) {
				return attentePaiement;
			}
		}
		
		protected void raiseAttentePaiement() {
			synchronized(DrinkingMachineStatemachine.this) {
				attentePaiement = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onAttentePaiementRaised();
				}
			}
		}
		
		private boolean erreurPaiment;
		
		
		public boolean isRaisedErreurPaiment() {
			synchronized(DrinkingMachineStatemachine.this) {
				return erreurPaiment;
			}
		}
		
		protected void raiseErreurPaiment() {
			synchronized(DrinkingMachineStatemachine.this) {
				erreurPaiment = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onErreurPaimentRaised();
				}
			}
		}
		
		private boolean isThereBoisson;
		
		public synchronized boolean getIsThereBoisson() {
			synchronized(DrinkingMachineStatemachine.this) {
				return isThereBoisson;
			}
		}
		
		public void setIsThereBoisson(boolean value) {
			synchronized(DrinkingMachineStatemachine.this) {
				this.isThereBoisson = value;
			}
		}
		
		protected void clearEvents() {
			cancelButton = false;
			boissonButton = false;
			slider = false;
			nFCButton = false;
			boissonPrete = false;
			coinButton = false;
			confirmationLiquide = false;
		}
		protected void clearOutEvents() {
		
		nettoyageText = false;
		doReset = false;
		prepareBoisson = false;
		enAttente = false;
		updateSlider = false;
		updateBoisson = false;
		finishText = false;
		lectureCarte = false;
		increaseCoin = false;
		renduMonnaie = false;
		paiementNFC = false;
		attentePaiement = false;
		erreurPaiment = false;
		}
		
	}
	
	
	protected SCInterfaceImpl sCInterface;
	
	private boolean initialized = false;
	
	public enum State {
		main_region_Demarrage,
		main_region_Pr_par_,
		main_region_En_pr_partation,
		main_region_GestionCommande,
		main_region_GestionCommande_chooseGestion_EnAttente,
		main_region_GestionCommande_resetTimer_reset,
		main_region_GestionCommande_paiementGestion_EnAttentePaiement,
		main_region_GestionCommande_paiementGestion_PaimentNFC,
		main_region_GestionCommande_paiementGestion_InsertionArgent,
		main_region_GestionCommande_paiementGestion_Pay_,
		main_region_GestionCommande_paiementGestion_LectureCarte,
		main_region_GestionCommande_paiementGestion_PaiementLiquide,
		$NullState$
	};
	
	private final State[] stateVector = new State[3];
	
	private int nextStateIndex;
	
	private ITimer timer;
	
	private final boolean[] timeEvents = new boolean[7];
	
	private BlockingQueue<Runnable> inEventQueue = new LinkedBlockingQueue<Runnable>();
	private boolean isRunningCycle = false;
	public DrinkingMachineStatemachine() {
		sCInterface = new SCInterfaceImpl();
	}
	
	public synchronized void init() {
		this.initialized = true;
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		for (int i = 0; i < 3; i++) {
			stateVector[i] = State.$NullState$;
		}
		clearEvents();
		clearOutEvents();
		sCInterface.setIsThereBoisson(false);
	}
	
	public synchronized void enter() {
		if (!initialized) {
			throw new IllegalStateException(
				"The state machine needs to be initialized first by calling the init() function."
			);
		}
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		enterSequence_main_region_default();
	}
	
	public synchronized void runCycle() {
		if (!initialized)
			throw new IllegalStateException(
					"The state machine needs to be initialized first by calling the init() function.");
		
		if (isRunningCycle) {
			return;
		}
		isRunningCycle = true;
		
		clearOutEvents();
	
		Runnable task = getNextEvent();
		if (task == null) {
			task = getDefaultEvent();
		}
		
		while (task != null) {
			task.run();
			clearEvents();
			task = getNextEvent();
		}
		
		isRunningCycle = false;
	}
	
	protected synchronized void singleCycle() {
		for (nextStateIndex = 0; nextStateIndex < stateVector.length; nextStateIndex++) {
			switch (stateVector[nextStateIndex]) {
				case main_region_Demarrage:
					main_region_Demarrage_react(true);
					break;
				case main_region_Pr_par_:
					main_region_Pr_par__react(true);
					break;
				case main_region_En_pr_partation:
					main_region_En_pr_partation_react(true);
					break;
				case main_region_GestionCommande_chooseGestion_EnAttente:
					main_region_GestionCommande_chooseGestion_EnAttente_react(true);
					break;
				case main_region_GestionCommande_resetTimer_reset:
					main_region_GestionCommande_resetTimer_reset_react(true);
					break;
				case main_region_GestionCommande_paiementGestion_EnAttentePaiement:
					main_region_GestionCommande_paiementGestion_EnAttentePaiement_react(true);
					break;
				case main_region_GestionCommande_paiementGestion_PaimentNFC:
					main_region_GestionCommande_paiementGestion_PaimentNFC_react(true);
					break;
				case main_region_GestionCommande_paiementGestion_InsertionArgent:
					main_region_GestionCommande_paiementGestion_InsertionArgent_react(true);
					break;
				case main_region_GestionCommande_paiementGestion_Pay_:
					main_region_GestionCommande_paiementGestion_Pay__react(true);
					break;
				case main_region_GestionCommande_paiementGestion_LectureCarte:
					main_region_GestionCommande_paiementGestion_LectureCarte_react(true);
					break;
				case main_region_GestionCommande_paiementGestion_PaiementLiquide:
					main_region_GestionCommande_paiementGestion_PaiementLiquide_react(true);
					break;
			default:
				// $NullState$
			}
		}
	}
	
	protected Runnable getNextEvent() {
		if(!inEventQueue.isEmpty()) {
			return inEventQueue.poll();
		}
		return null;
	}
	
	protected Runnable getDefaultEvent() {
		return new Runnable() {
			@Override
			public void run() {
				singleCycle();
			}
		};
	}
	
	public synchronized void exit() {
		exitSequence_main_region();
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public synchronized boolean isActive() {
		return stateVector[0] != State.$NullState$||stateVector[1] != State.$NullState$||stateVector[2] != State.$NullState$;
	}
	
	/** 
	* Always returns 'false' since this state machine can never become final.
	*
	* @see IStatemachine#isFinal()
	*/
	public synchronized boolean isFinal() {
		return false;
	}
	/**
	* This method resets the incoming events (time events included).
	*/
	protected void clearEvents() {
		sCInterface.clearEvents();
		for (int i=0; i<timeEvents.length; i++) {
			timeEvents[i] = false;
		}
	}
	
	/**
	* This method resets the outgoing events.
	*/
	protected void clearOutEvents() {
		sCInterface.clearOutEvents();
	}
	
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public synchronized boolean isStateActive(State state) {
	
		switch (state) {
		case main_region_Demarrage:
			return stateVector[0] == State.main_region_Demarrage;
		case main_region_Pr_par_:
			return stateVector[0] == State.main_region_Pr_par_;
		case main_region_En_pr_partation:
			return stateVector[0] == State.main_region_En_pr_partation;
		case main_region_GestionCommande:
			return stateVector[0].ordinal() >= State.
					main_region_GestionCommande.ordinal()&& stateVector[0].ordinal() <= State.main_region_GestionCommande_paiementGestion_PaiementLiquide.ordinal();
		case main_region_GestionCommande_chooseGestion_EnAttente:
			return stateVector[0] == State.main_region_GestionCommande_chooseGestion_EnAttente;
		case main_region_GestionCommande_resetTimer_reset:
			return stateVector[1] == State.main_region_GestionCommande_resetTimer_reset;
		case main_region_GestionCommande_paiementGestion_EnAttentePaiement:
			return stateVector[2] == State.main_region_GestionCommande_paiementGestion_EnAttentePaiement;
		case main_region_GestionCommande_paiementGestion_PaimentNFC:
			return stateVector[2] == State.main_region_GestionCommande_paiementGestion_PaimentNFC;
		case main_region_GestionCommande_paiementGestion_InsertionArgent:
			return stateVector[2] == State.main_region_GestionCommande_paiementGestion_InsertionArgent;
		case main_region_GestionCommande_paiementGestion_Pay_:
			return stateVector[2] == State.main_region_GestionCommande_paiementGestion_Pay_;
		case main_region_GestionCommande_paiementGestion_LectureCarte:
			return stateVector[2] == State.main_region_GestionCommande_paiementGestion_LectureCarte;
		case main_region_GestionCommande_paiementGestion_PaiementLiquide:
			return stateVector[2] == State.main_region_GestionCommande_paiementGestion_PaiementLiquide;
		default:
			return false;
		}
	}
	
	/**
	* Set the {@link ITimer} for the state machine. It must be set
	* externally on a timed state machine before a run cycle can be correctly
	* executed.
	* 
	* @param timer
	*/
	public synchronized void setTimer(ITimer timer) {
		this.timer = timer;
	}
	
	/**
	* Returns the currently used timer.
	* 
	* @return {@link ITimer}
	*/
	public ITimer getTimer() {
		return timer;
	}
	
	public synchronized void timeElapsed(int eventID) {
		inEventQueue.add(new Runnable() {
			@Override
			public void run() {
				timeEvents[eventID] = true;
				singleCycle();
			}
		});
		runCycle();
	}
	
	public SCInterface getSCInterface() {
		return sCInterface;
	}
	
	public synchronized void raiseCancelButton() {
		sCInterface.raiseCancelButton();
	}
	
	public synchronized void raiseBoissonButton() {
		sCInterface.raiseBoissonButton();
	}
	
	public synchronized void raiseSlider() {
		sCInterface.raiseSlider();
	}
	
	public synchronized void raiseNFCButton() {
		sCInterface.raiseNFCButton();
	}
	
	public synchronized void raiseBoissonPrete() {
		sCInterface.raiseBoissonPrete();
	}
	
	public synchronized void raiseCoinButton() {
		sCInterface.raiseCoinButton();
	}
	
	public synchronized void raiseConfirmationLiquide() {
		sCInterface.raiseConfirmationLiquide();
	}
	
	public synchronized boolean isRaisedNettoyageText() {
		return sCInterface.isRaisedNettoyageText();
	}
	
	public synchronized boolean isRaisedDoReset() {
		return sCInterface.isRaisedDoReset();
	}
	
	public synchronized boolean isRaisedPrepareBoisson() {
		return sCInterface.isRaisedPrepareBoisson();
	}
	
	public synchronized boolean isRaisedEnAttente() {
		return sCInterface.isRaisedEnAttente();
	}
	
	public synchronized boolean isRaisedUpdateSlider() {
		return sCInterface.isRaisedUpdateSlider();
	}
	
	public synchronized boolean isRaisedUpdateBoisson() {
		return sCInterface.isRaisedUpdateBoisson();
	}
	
	public synchronized boolean isRaisedFinishText() {
		return sCInterface.isRaisedFinishText();
	}
	
	public synchronized boolean isRaisedLectureCarte() {
		return sCInterface.isRaisedLectureCarte();
	}
	
	public synchronized boolean isRaisedIncreaseCoin() {
		return sCInterface.isRaisedIncreaseCoin();
	}
	
	public synchronized boolean isRaisedRenduMonnaie() {
		return sCInterface.isRaisedRenduMonnaie();
	}
	
	public synchronized boolean isRaisedPaiementNFC() {
		return sCInterface.isRaisedPaiementNFC();
	}
	
	public synchronized boolean isRaisedAttentePaiement() {
		return sCInterface.isRaisedAttentePaiement();
	}
	
	public synchronized boolean isRaisedErreurPaiment() {
		return sCInterface.isRaisedErreurPaiment();
	}
	
	public synchronized boolean getIsThereBoisson() {
		return sCInterface.getIsThereBoisson();
	}
	
	public synchronized void setIsThereBoisson(boolean value) {
		sCInterface.setIsThereBoisson(value);
	}
	
	/* Entry action for state 'Demarrage'. */
	private void entryAction_main_region_Demarrage() {
		timer.setTimer(this, 0, 2500, false);
	}
	
	/* Entry action for state 'Préparé'. */
	private void entryAction_main_region_Pr_par_() {
		timer.setTimer(this, 1, (5 * 1000), false);
	}
	
	/* Entry action for state 'reset'. */
	private void entryAction_main_region_GestionCommande_resetTimer_reset() {
		timer.setTimer(this, 2, (45 * 1000), false);
	}
	
	/* Entry action for state 'PaimentNFC'. */
	private void entryAction_main_region_GestionCommande_paiementGestion_PaimentNFC() {
		timer.setTimer(this, 3, 10, true);
	}
	
	/* Entry action for state 'Payé'. */
	private void entryAction_main_region_GestionCommande_paiementGestion_Pay_() {
		timer.setTimer(this, 4, (2 * 1000), false);
	}
	
	/* Entry action for state 'LectureCarte'. */
	private void entryAction_main_region_GestionCommande_paiementGestion_LectureCarte() {
		timer.setTimer(this, 5, (3 * 1000), false);
	}
	
	/* Entry action for state 'PaiementLiquide'. */
	private void entryAction_main_region_GestionCommande_paiementGestion_PaiementLiquide() {
		timer.setTimer(this, 6, 10, true);
	}
	
	/* Exit action for state 'Demarrage'. */
	private void exitAction_main_region_Demarrage() {
		timer.unsetTimer(this, 0);
	}
	
	/* Exit action for state 'Préparé'. */
	private void exitAction_main_region_Pr_par_() {
		timer.unsetTimer(this, 1);
	}
	
	/* Exit action for state 'reset'. */
	private void exitAction_main_region_GestionCommande_resetTimer_reset() {
		timer.unsetTimer(this, 2);
	}
	
	/* Exit action for state 'PaimentNFC'. */
	private void exitAction_main_region_GestionCommande_paiementGestion_PaimentNFC() {
		timer.unsetTimer(this, 3);
	}
	
	/* Exit action for state 'Payé'. */
	private void exitAction_main_region_GestionCommande_paiementGestion_Pay_() {
		timer.unsetTimer(this, 4);
	}
	
	/* Exit action for state 'LectureCarte'. */
	private void exitAction_main_region_GestionCommande_paiementGestion_LectureCarte() {
		timer.unsetTimer(this, 5);
	}
	
	/* Exit action for state 'PaiementLiquide'. */
	private void exitAction_main_region_GestionCommande_paiementGestion_PaiementLiquide() {
		timer.unsetTimer(this, 6);
	}
	
	/* 'default' enter sequence for state Demarrage */
	private void enterSequence_main_region_Demarrage_default() {
		entryAction_main_region_Demarrage();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_Demarrage;
	}
	
	/* 'default' enter sequence for state Préparé */
	private void enterSequence_main_region_Pr_par__default() {
		entryAction_main_region_Pr_par_();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_Pr_par_;
	}
	
	/* 'default' enter sequence for state En prépartation */
	private void enterSequence_main_region_En_pr_partation_default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_En_pr_partation;
	}
	
	/* 'default' enter sequence for state GestionCommande */
	private void enterSequence_main_region_GestionCommande_default() {
		enterSequence_main_region_GestionCommande_chooseGestion_default();
		enterSequence_main_region_GestionCommande_resetTimer_default();
		enterSequence_main_region_GestionCommande_paiementGestion_default();
	}
	
	/* 'default' enter sequence for state EnAttente */
	private void enterSequence_main_region_GestionCommande_chooseGestion_EnAttente_default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_GestionCommande_chooseGestion_EnAttente;
	}
	
	/* 'default' enter sequence for state reset */
	private void enterSequence_main_region_GestionCommande_resetTimer_reset_default() {
		entryAction_main_region_GestionCommande_resetTimer_reset();
		nextStateIndex = 1;
		stateVector[1] = State.main_region_GestionCommande_resetTimer_reset;
	}
	
	/* 'default' enter sequence for state EnAttentePaiement */
	private void enterSequence_main_region_GestionCommande_paiementGestion_EnAttentePaiement_default() {
		nextStateIndex = 2;
		stateVector[2] = State.main_region_GestionCommande_paiementGestion_EnAttentePaiement;
	}
	
	/* 'default' enter sequence for state PaimentNFC */
	private void enterSequence_main_region_GestionCommande_paiementGestion_PaimentNFC_default() {
		entryAction_main_region_GestionCommande_paiementGestion_PaimentNFC();
		nextStateIndex = 2;
		stateVector[2] = State.main_region_GestionCommande_paiementGestion_PaimentNFC;
	}
	
	/* 'default' enter sequence for state InsertionArgent */
	private void enterSequence_main_region_GestionCommande_paiementGestion_InsertionArgent_default() {
		nextStateIndex = 2;
		stateVector[2] = State.main_region_GestionCommande_paiementGestion_InsertionArgent;
	}
	
	/* 'default' enter sequence for state Payé */
	private void enterSequence_main_region_GestionCommande_paiementGestion_Pay__default() {
		entryAction_main_region_GestionCommande_paiementGestion_Pay_();
		nextStateIndex = 2;
		stateVector[2] = State.main_region_GestionCommande_paiementGestion_Pay_;
	}
	
	/* 'default' enter sequence for state LectureCarte */
	private void enterSequence_main_region_GestionCommande_paiementGestion_LectureCarte_default() {
		entryAction_main_region_GestionCommande_paiementGestion_LectureCarte();
		nextStateIndex = 2;
		stateVector[2] = State.main_region_GestionCommande_paiementGestion_LectureCarte;
	}
	
	/* 'default' enter sequence for state PaiementLiquide */
	private void enterSequence_main_region_GestionCommande_paiementGestion_PaiementLiquide_default() {
		entryAction_main_region_GestionCommande_paiementGestion_PaiementLiquide();
		nextStateIndex = 2;
		stateVector[2] = State.main_region_GestionCommande_paiementGestion_PaiementLiquide;
	}
	
	/* 'default' enter sequence for region main region */
	private void enterSequence_main_region_default() {
		react_main_region__entry_Default();
	}
	
	/* 'default' enter sequence for region chooseGestion */
	private void enterSequence_main_region_GestionCommande_chooseGestion_default() {
		react_main_region_GestionCommande_chooseGestion__entry_Default();
	}
	
	/* 'default' enter sequence for region resetTimer */
	private void enterSequence_main_region_GestionCommande_resetTimer_default() {
		react_main_region_GestionCommande_resetTimer__entry_Default();
	}
	
	/* 'default' enter sequence for region paiementGestion */
	private void enterSequence_main_region_GestionCommande_paiementGestion_default() {
		react_main_region_GestionCommande_paiementGestion__entry_Default();
	}
	
	/* Default exit sequence for state Demarrage */
	private void exitSequence_main_region_Demarrage() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_main_region_Demarrage();
	}
	
	/* Default exit sequence for state Préparé */
	private void exitSequence_main_region_Pr_par_() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_main_region_Pr_par_();
	}
	
	/* Default exit sequence for state En prépartation */
	private void exitSequence_main_region_En_pr_partation() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state GestionCommande */
	private void exitSequence_main_region_GestionCommande() {
		exitSequence_main_region_GestionCommande_chooseGestion();
		exitSequence_main_region_GestionCommande_resetTimer();
		exitSequence_main_region_GestionCommande_paiementGestion();
	}
	
	/* Default exit sequence for state EnAttente */
	private void exitSequence_main_region_GestionCommande_chooseGestion_EnAttente() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state reset */
	private void exitSequence_main_region_GestionCommande_resetTimer_reset() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
		
		exitAction_main_region_GestionCommande_resetTimer_reset();
	}
	
	/* Default exit sequence for state EnAttentePaiement */
	private void exitSequence_main_region_GestionCommande_paiementGestion_EnAttentePaiement() {
		nextStateIndex = 2;
		stateVector[2] = State.$NullState$;
	}
	
	/* Default exit sequence for state PaimentNFC */
	private void exitSequence_main_region_GestionCommande_paiementGestion_PaimentNFC() {
		nextStateIndex = 2;
		stateVector[2] = State.$NullState$;
		
		exitAction_main_region_GestionCommande_paiementGestion_PaimentNFC();
	}
	
	/* Default exit sequence for state InsertionArgent */
	private void exitSequence_main_region_GestionCommande_paiementGestion_InsertionArgent() {
		nextStateIndex = 2;
		stateVector[2] = State.$NullState$;
	}
	
	/* Default exit sequence for state Payé */
	private void exitSequence_main_region_GestionCommande_paiementGestion_Pay_() {
		nextStateIndex = 2;
		stateVector[2] = State.$NullState$;
		
		exitAction_main_region_GestionCommande_paiementGestion_Pay_();
	}
	
	/* Default exit sequence for state LectureCarte */
	private void exitSequence_main_region_GestionCommande_paiementGestion_LectureCarte() {
		nextStateIndex = 2;
		stateVector[2] = State.$NullState$;
		
		exitAction_main_region_GestionCommande_paiementGestion_LectureCarte();
	}
	
	/* Default exit sequence for state PaiementLiquide */
	private void exitSequence_main_region_GestionCommande_paiementGestion_PaiementLiquide() {
		nextStateIndex = 2;
		stateVector[2] = State.$NullState$;
		
		exitAction_main_region_GestionCommande_paiementGestion_PaiementLiquide();
	}
	
	/* Default exit sequence for region main region */
	private void exitSequence_main_region() {
		switch (stateVector[0]) {
		case main_region_Demarrage:
			exitSequence_main_region_Demarrage();
			break;
		case main_region_Pr_par_:
			exitSequence_main_region_Pr_par_();
			break;
		case main_region_En_pr_partation:
			exitSequence_main_region_En_pr_partation();
			break;
		case main_region_GestionCommande_chooseGestion_EnAttente:
			exitSequence_main_region_GestionCommande_chooseGestion_EnAttente();
			break;
		default:
			break;
		}
		
		switch (stateVector[1]) {
		case main_region_GestionCommande_resetTimer_reset:
			exitSequence_main_region_GestionCommande_resetTimer_reset();
			break;
		default:
			break;
		}
		
		switch (stateVector[2]) {
		case main_region_GestionCommande_paiementGestion_EnAttentePaiement:
			exitSequence_main_region_GestionCommande_paiementGestion_EnAttentePaiement();
			break;
		case main_region_GestionCommande_paiementGestion_PaimentNFC:
			exitSequence_main_region_GestionCommande_paiementGestion_PaimentNFC();
			break;
		case main_region_GestionCommande_paiementGestion_InsertionArgent:
			exitSequence_main_region_GestionCommande_paiementGestion_InsertionArgent();
			break;
		case main_region_GestionCommande_paiementGestion_Pay_:
			exitSequence_main_region_GestionCommande_paiementGestion_Pay_();
			break;
		case main_region_GestionCommande_paiementGestion_LectureCarte:
			exitSequence_main_region_GestionCommande_paiementGestion_LectureCarte();
			break;
		case main_region_GestionCommande_paiementGestion_PaiementLiquide:
			exitSequence_main_region_GestionCommande_paiementGestion_PaiementLiquide();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region chooseGestion */
	private void exitSequence_main_region_GestionCommande_chooseGestion() {
		switch (stateVector[0]) {
		case main_region_GestionCommande_chooseGestion_EnAttente:
			exitSequence_main_region_GestionCommande_chooseGestion_EnAttente();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region resetTimer */
	private void exitSequence_main_region_GestionCommande_resetTimer() {
		switch (stateVector[1]) {
		case main_region_GestionCommande_resetTimer_reset:
			exitSequence_main_region_GestionCommande_resetTimer_reset();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region paiementGestion */
	private void exitSequence_main_region_GestionCommande_paiementGestion() {
		switch (stateVector[2]) {
		case main_region_GestionCommande_paiementGestion_EnAttentePaiement:
			exitSequence_main_region_GestionCommande_paiementGestion_EnAttentePaiement();
			break;
		case main_region_GestionCommande_paiementGestion_PaimentNFC:
			exitSequence_main_region_GestionCommande_paiementGestion_PaimentNFC();
			break;
		case main_region_GestionCommande_paiementGestion_InsertionArgent:
			exitSequence_main_region_GestionCommande_paiementGestion_InsertionArgent();
			break;
		case main_region_GestionCommande_paiementGestion_Pay_:
			exitSequence_main_region_GestionCommande_paiementGestion_Pay_();
			break;
		case main_region_GestionCommande_paiementGestion_LectureCarte:
			exitSequence_main_region_GestionCommande_paiementGestion_LectureCarte();
			break;
		case main_region_GestionCommande_paiementGestion_PaiementLiquide:
			exitSequence_main_region_GestionCommande_paiementGestion_PaiementLiquide();
			break;
		default:
			break;
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region__entry_Default() {
		enterSequence_main_region_Demarrage_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_GestionCommande_chooseGestion__entry_Default() {
		enterSequence_main_region_GestionCommande_chooseGestion_EnAttente_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_GestionCommande_resetTimer__entry_Default() {
		enterSequence_main_region_GestionCommande_resetTimer_reset_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_GestionCommande_paiementGestion__entry_Default() {
		enterSequence_main_region_GestionCommande_paiementGestion_EnAttentePaiement_default();
	}
	
	private boolean react() {
		return false;
	}
	
	private boolean main_region_Demarrage_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[0]) {
				exitSequence_main_region_Demarrage();
				sCInterface.raiseEnAttente();
				
				sCInterface.setIsThereBoisson(false);
				
				enterSequence_main_region_GestionCommande_default();
				react();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_Pr_par__react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[1]) {
				exitSequence_main_region_Pr_par_();
				sCInterface.raiseNettoyageText();
				
				enterSequence_main_region_Demarrage_default();
				react();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_En_pr_partation_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.boissonPrete) {
				exitSequence_main_region_En_pr_partation();
				sCInterface.raiseFinishText();
				
				enterSequence_main_region_Pr_par__default();
				react();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_GestionCommande_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.cancelButton) {
				exitSequence_main_region_GestionCommande();
				sCInterface.raiseDoReset();
				
				enterSequence_main_region_Demarrage_default();
				react();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_GestionCommande_chooseGestion_EnAttente_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.slider) {
				exitSequence_main_region_GestionCommande_chooseGestion_EnAttente();
				sCInterface.raiseUpdateSlider();
				
				enterSequence_main_region_GestionCommande_chooseGestion_EnAttente_default();
			} else {
				if (sCInterface.boissonButton) {
					exitSequence_main_region_GestionCommande_chooseGestion_EnAttente();
					sCInterface.raiseUpdateBoisson();
					
					sCInterface.setIsThereBoisson(true);
					
					enterSequence_main_region_GestionCommande_chooseGestion_EnAttente_default();
				} else {
					did_transition = false;
				}
			}
		}
		return did_transition;
	}
	
	private boolean main_region_GestionCommande_resetTimer_reset_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[2]) {
				exitSequence_main_region_GestionCommande();
				sCInterface.raiseDoReset();
				
				enterSequence_main_region_Demarrage_default();
				react();
			} else {
				if ((sCInterface.boissonButton || (sCInterface.slider || (sCInterface.nFCButton || sCInterface.coinButton)))) {
					exitSequence_main_region_GestionCommande_resetTimer_reset();
					enterSequence_main_region_GestionCommande_resetTimer_reset_default();
				} else {
					did_transition = false;
				}
			}
		}
		return did_transition;
	}
	
	private boolean main_region_GestionCommande_paiementGestion_EnAttentePaiement_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.nFCButton) {
				exitSequence_main_region_GestionCommande_paiementGestion_EnAttentePaiement();
				sCInterface.raiseLectureCarte();
				
				enterSequence_main_region_GestionCommande_paiementGestion_LectureCarte_default();
				main_region_GestionCommande_react(false);
			} else {
				if (sCInterface.coinButton) {
					exitSequence_main_region_GestionCommande_paiementGestion_EnAttentePaiement();
					sCInterface.raiseIncreaseCoin();
					
					enterSequence_main_region_GestionCommande_paiementGestion_InsertionArgent_default();
					main_region_GestionCommande_react(false);
				} else {
					did_transition = false;
				}
			}
		}
		if (did_transition==false) {
			did_transition = main_region_GestionCommande_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_GestionCommande_paiementGestion_PaimentNFC_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (((timeEvents[3]) && (sCInterface.getIsThereBoisson()))) {
				exitSequence_main_region_GestionCommande_paiementGestion_PaimentNFC();
				sCInterface.raisePaiementNFC();
				
				enterSequence_main_region_GestionCommande_paiementGestion_Pay__default();
				main_region_GestionCommande_react(false);
			} else {
				if (sCInterface.coinButton) {
					exitSequence_main_region_GestionCommande_paiementGestion_PaimentNFC();
					sCInterface.raiseErreurPaiment();
					
					enterSequence_main_region_GestionCommande_paiementGestion_PaimentNFC_default();
				} else {
					did_transition = false;
				}
			}
		}
		if (did_transition==false) {
			did_transition = main_region_GestionCommande_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_GestionCommande_paiementGestion_InsertionArgent_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.coinButton) {
				exitSequence_main_region_GestionCommande_paiementGestion_InsertionArgent();
				sCInterface.raiseIncreaseCoin();
				
				enterSequence_main_region_GestionCommande_paiementGestion_InsertionArgent_default();
			} else {
				if (sCInterface.nFCButton) {
					exitSequence_main_region_GestionCommande_paiementGestion_InsertionArgent();
					sCInterface.raiseErreurPaiment();
					
					enterSequence_main_region_GestionCommande_paiementGestion_InsertionArgent_default();
				} else {
					if (sCInterface.confirmationLiquide) {
						exitSequence_main_region_GestionCommande_paiementGestion_InsertionArgent();
						enterSequence_main_region_GestionCommande_paiementGestion_PaiementLiquide_default();
						main_region_GestionCommande_react(false);
					} else {
						did_transition = false;
					}
				}
			}
		}
		if (did_transition==false) {
			did_transition = main_region_GestionCommande_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_GestionCommande_paiementGestion_Pay__react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[4]) {
				exitSequence_main_region_GestionCommande();
				sCInterface.raisePrepareBoisson();
				
				enterSequence_main_region_En_pr_partation_default();
				react();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = main_region_GestionCommande_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_GestionCommande_paiementGestion_LectureCarte_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[5]) {
				exitSequence_main_region_GestionCommande_paiementGestion_LectureCarte();
				sCInterface.raiseAttentePaiement();
				
				enterSequence_main_region_GestionCommande_paiementGestion_PaimentNFC_default();
				main_region_GestionCommande_react(false);
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = main_region_GestionCommande_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_GestionCommande_paiementGestion_PaiementLiquide_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (((timeEvents[6]) && (sCInterface.getIsThereBoisson()))) {
				exitSequence_main_region_GestionCommande_paiementGestion_PaiementLiquide();
				sCInterface.raiseRenduMonnaie();
				
				enterSequence_main_region_GestionCommande_paiementGestion_Pay__default();
				main_region_GestionCommande_react(false);
			} else {
				if (sCInterface.nFCButton) {
					exitSequence_main_region_GestionCommande_paiementGestion_PaiementLiquide();
					sCInterface.raiseErreurPaiment();
					
					enterSequence_main_region_GestionCommande_paiementGestion_PaiementLiquide_default();
				} else {
					did_transition = false;
				}
			}
		}
		if (did_transition==false) {
			did_transition = main_region_GestionCommande_react(try_transition);
		}
		return did_transition;
	}
	
}
