/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.project.drinkingmachine;

import fr.univcotedazur.polytech.si4.fsm.project.IStatemachine;
import fr.univcotedazur.polytech.si4.fsm.project.ITimerCallback;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public interface IDrinkingMachineStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseCancelButton();
		
		public void raiseCoffeeButton();
		
		public void raiseSlider();
		
		public void raiseNFCButton();
		
		public void raiseBoissonPrete();
		
		public boolean isRaisedNettoyageText();
		
		public boolean isRaisedDoReset();
		
		public boolean isRaisedPrepareBoisson();
		
		public boolean isRaisedEnAttente();
		
		public boolean isRaisedUpdateBoisson();
		
		public boolean isRaisedFinishText();
		
	public List<SCInterfaceListener> getListeners();
	}
	
	public interface SCInterfaceListener {
	
		public void onNettoyageTextRaised();
		public void onDoResetRaised();
		public void onPrepareBoissonRaised();
		public void onEnAttenteRaised();
		public void onUpdateBoissonRaised();
		public void onFinishTextRaised();
		}
	
	public SCInterface getSCInterface();
	
}
